hook.Add("gRust.Loaded", "gRust.InitMultipliers", function()
	gRust.CreateConfigValue("farming/gather.multiplier", 1, true)
	gRust.CreateConfigValue("building/resources.multiplier", 1, true)
	gRust.CreateConfigValue("recycler/efficiency.multiplier", 1, true)
	gRust.CreateConfigValue("loot/multiplier", 1, true)
end)
